"use strict";

module.exports = {
    config: {
	opacity: 0.8,
        updateChannel: 'stable',
        fontSize: 16,
        fontFamily: '"Fira Code", Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',
        fontWeight: 'normal',
        fontWeightBold: 'bold',
        lineHeight: 0,
        letterSpacing: 0,
        cursorColor: 'rgba(255,255,255,0.8)',
        cursorAccentColor: '#000',
        cursorShape: 'BEAM',
        cursorBlink: true,
        foregroundColor: '#F7F8FF',
        backgroundColor: '#2B2C36',
        selectionColor: 'rgba(92, 100, 255,0.3)',
        borderColor: '#3c3e4d00',
        css: 'color: gray;',
        termCSS: '',
        workingDirectory: '%USERPROFILE%',
        showHamburgerMenu: '',
        showWindowControls: '',
        padding: '20px',
        colors: {
            black: '#2B2C36',
            red: '#C51E14',
            green: '#1DC121',
            yellow: '#C7C329',
            blue: '#0A2FC4',
            magenta: '#C839C5',
            cyan: '#20C5C6',
            white: '#F7F8FF',
            lightBlack: '#686868',
            lightRed: '#FD6F6B',
            lightGreen: '#67F86F',
            lightYellow: '#FFFA72',
            lightBlue: '#6A76FB',
            lightMagenta: '#FD7CFC',
            lightCyan: '#68FDFE',
            lightWhite: '#FFFFFF',
            limeGreen: '#32CD32',
            lightCoral: '#F08080',
        },
        shell: 'C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe',
        shellArgs: [''],
        env: {},
        bell: 'SOUND',
        copyOnSelect: false,
        defaultSSHApp: true,
        quickEdit: false,
        macOptionSelectionMode: 'vertical',
        webGLRenderer: false,
        webLinksActivationKey: 'ctrl',
        disableLigatures: false,
        disableAutoUpdates: false,
    },
    plugins: [],
    localPlugins: [],
    keymaps: {},
};
//# sourceMappingURL=config-default.js.map