[[language]]
name = "typescript"
file-types = ["ts", "tsx"]
language-servers = [ "typescript-language-server", "emmet-ls", "tailwindcss-ls" ]
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "tsx"
file-types = ["ts", "tsx"]
language-servers = [ "typescript-language-server", "emmet-ls", "tailwindcss-ls" ]
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "css"
language-servers = ["vscode-css-language-server", "talwindcss-ls"]

[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "talwindcss-ls"]
