[[language]]
name = "typescript"
formatter = { command = 'C:\\Program Files\\nodejs\\prettier.cmd', args = ["--parser", "typescript"] }

[[language]]
name = "tsx"
formatter = { command = 'C:\\Program Files\\nodejs\\prettier.cmd', args = ["--parser", "babel-ts"] }

[[language]]
name = "html"
formatter = { command = 'C:\\Program Files\\nodejs\\prettier.cmd', args = ["--parser", "html"] }

[[language]]
name = "json"
formatter = { command = 'C:\\Program Files\\nodejs\\prettier.cmd', args = ["--parser", "json"] }

[[language]]
name = "css"
formatter = { command = 'C:\\Program Files\\nodejs\\prettier.cmd', args = ["--parser", "css"] }

[[language]]
name = "javascript"
formatter = { command = 'C:\\Program Files\\nodejs\\prettier.cmd', args = ["--parser", "typescript"] }
