set nu
set rnu
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set smartindent
set autoindent
set noautochdir
set nowrap
set smartcase
set ignorecase
set hidden
set splitbelow
set splitright
set nocursorline
set hlsearch
set incsearch
set path+=**
set wildignore+=**/node_modules/**
set wildignore+=**/dist/**
set wildignore+=**/build/**
set wildignore+=**/bin/**
set wildignore+=**/obj/**
colorscheme default

filetype plugin indent on
filetype plugin detect
syntax on

hi Comment ctermfg=green
hi String ctermfg=120
hi Macro ctermfg=red
hi Number ctermfg=5

" copy selection to clipboard
vnoremap <c-c> :w !clip.exe<CR>
" copy the entire file to clipboard
nnoremap <c-c> :w !clip.exe<CR>
nnoremap <c-i> :%!prettier % --config .prettierrc<CR>
