set nu
set rnu
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set smartindent
set autoindent
set path+=**
set noautochdir
set nowrap
set smartcase
set ignorecase
set hidden
set splitbelow
set splitright
set nocursorline
set hlsearch
set incsearch
colorscheme default

filetype plugin indent on
filetype plugin detect
syntax on

hi Comment ctermfg=green
hi String ctermfg=120
hi Macro ctermfg=red
hi Number ctermfg=5

" copy selection to clipboard
vnoremap <c-c> :w !clip.exe<CR>
" copy the entire file to clipboard
nnoremap <c-c> :w !clip.exe<CR>
" format js files, npm i -g prettier@latest
nnoremap <c-i> :%!prettier % --config .prettierrc<CR>
