set nu
set rnu
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set smartindent
set autoindent
set path+=**
set nowrap
set smartcase
set ignorecase
set hidden
set splitbelow
set splitright
set nocursorline
set clipboard+=unamedplus

filetype plugin indent on
filetype plugin detect
syntax on

hi Comment ctermfg=green
hi String ctermfg=120
hi Macro ctermfg=red
hi Number ctermfg=5
